# Generated by Django 4.2.1 on 2023-06-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_destination_pais_itinerary_destination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=8),
        ),
    ]
